#ifndef ERROR_CODES_H
#define ERROR_CODES_H

enum {
    NO_COMMAND = 1,
    NO_ARGUMENTS,
    INVALID_ASSEMBLY,
    //compile command
    CMP_NO_ARGUMENTS,
    CMP_NO_FILE_EXTENSION,
    CMP_NO_COMPILABLE_FILE,
    CMP_INVALID_FILE_FOR_THIS,
    CMP_NO_INPUT_FILES,
    CMP_INVALID_ASM_ARGUMENT_SYNTAX,
    //NIR compile command
    //UTF-8 compatibily
    UTF8_ALLOC_ERROR,
    UTF8_ALLOC_SEQUENCE_ERROR,
    UTF8_REALLOC_SEQUENCE_ERROR,
    UTF8_INVALID_INDEX_SIZE,
    UTF8_INVALID_CHARACTER,
    UTF8_NO_CONTINUATION_BYTE,
    UTF8_OVERLONG,
    UTF8_SURROGATE_PAIR,
    UTF8_AWAY_LIMITS,
};

#endif